name: Basic verify

on:
  pull_request:
    branches: 
      - "main"
      - "RN"
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  compile-check:
    runs-on: windows-2022
    env:
      CONFIGURATION: FinalAlertDebug YR

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive
        lfs: true
    - name: setup-msvc
      uses: egor-tensin/vs-shell@v2
      with:
        # Target architecture
        arch: x64
    - name: build-msvc
      run: |
        devenv.com "MissionEditor.sln"  /Build "${{ env.CONFIGURATION }}|x64" /project UnitTest
    - name: do UT
      run: |
        cd x64\Debug
        ./UnitTest